### ISSUE TITLE
GBM version?

### ISSUE THREAD

**Issue by ghost** [XayOn/docker-kodi-beta#1]
HI

I am VERY interested in this, as it would allow me to run kodi on a stable debian system (which is pretty hard atm since debian ships old drm and mesa packages). However, I am also very much after HDR playback, and this afaik will only be supported on gbm. Would this be possible?

Also, an example docker-compose.yaml would be nice

**Comment by XayOn** [comment]
Hi elfhack, thanks for you feedback.
I've been trying to get the multiprocessor thing working for a while, I've just uploaded an experimental commit with GDM support, if the build (with the multiprocessor thing too) works, it should push an image tagged "gbm", wich you should be able to test then :smile: 

About the compose stuff, making X11 apps working on docker-compose is hard, I'm interested in it myself, help on that would be greatly appreciated. That would actually allow me to use it on bacchus ( https://github.com/xayon/bacchus )

**Comment by ghost** [comment]
> About the compose stuff, making X11 apps working on docker-compose is hard, I'm interested in it myself, help on that would be greatly appreciated. That would actually allow me to use it on bacchus ( https://github.com/xayon/bacchus )

See that's the thing. GBM is X-less, it runs directly on KMS with no windowing server at all. Perfect for dedicated htpc, this is how libreelec does this (well, ok except for x86, but only until kodi 19). However, i have no idea how one would run such a container in regards to hardware access. I think docker run -privileged would be a starting point here

**Comment by XayOn** [comment]
Seems like there is a privileged: true that could do the trick, I'm not sure if I could check it this week though.
And the GBM build is currently failing on the CI.

**Comment by XayOn** [comment]
After adding security repo and installing the current linux headers, it seems to work. Im buildin a gles version and a gl version.

**Comment by ghost** [comment]
Don't bother with the gles version, that's mostly for SBCs. On x86 we only need the GL version

**Comment by XayOn** [comment]
@elfhack You can test it now.
I've been able to run it on my intel NUC, both with plain docker and with docker-compose.

I'll add it to the docs soon:

`docker run -P8080:8080 --restart=always --privileged xayon/docker-kodi-beta:gbm`

```  
kodi:
     restart: always
     image: xayon/docker-kodi-beta:gbm 
     privileged: True
     ports:
      - 8080:8080```

**Comment by ghost** [comment]
@XayOn Just tried it out, it's very promising and does indeed start. However

- We're missing intel libva libraries in the container (intel-media-va-driver-non-free would be preferable)
- We should allow the user to specify the Fullrange option (basically settings this https://kodi.wiki/view/Video_levels_and_color_space - in gbm land, this is done by 
- A non-root user would be preferable if possible

I'm not seing the gbm dockerfile in the repo yet, would love to post patches :/

**Comment by XayOn** [comment]
Hi @elfhack  Thanks.

- Regarding the libva libraries (drivers), is there a reasoning behind including the driver directly in a container? I'm not getting the whole VAAPI thing.
- You left the fullrange-GBM part unfinished, and I'm not familiar with video levels and colorspace.
- I'm opening an issue for the non-root user part

There's no differenciated Dockerfile for the GBM build, it's done with a flag on the CI, you can see it in the current Dockerfile (ARGS FLAGS line) and on .github/workflows.

Only the first image wasn't done this way. I believe a public CI system with hashes that you can actually check is essential on this kind of projects.

Thanks for your feedback

**Comment by XayOn** [comment]
@elfhack Could you please open issues for the fullrange and libva things so we can follow up there?

**Comment by ghost** [comment]
For vaapi, you need the drivers, libva only handles the API (i think?). Kodi even complains about missing iHD_drv_video.so/i965_drv_video.so when starting up in gbm mode. I'd imagine you need equivalents for AMD as well - mesa-va-drivers.

Yeah, fullrange is usually done with xrandr, but with gbm there is no xrandr to speak of. However, a couple of years ago I used a custom gentoo box and I had a method for doing this, I just need to dig it up.

I'll submit both in a while when I have all the pieces setup
